jobs:
- job: Test
  pool:
    name: default
    demands:
      agent.name -equals ubuntu-build-server  
  steps:
  - task: NodeTool@0 
    inputs:
      versionSpec: '10.x'
  - script: |
      npm install
      npx tslint --project ./
      npx tsc

      
