jobs:
- job: Test
  pool:
    name: default
    demands:
      agent.name -equals ubuntu-build-server  
  steps:
  - task: NodeTool@0 
    inputs:
      versionSpec: '12.x'
  - script: |
      yarn install
      yarn eslint --quiet ./
      yarn next build
