# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql
    restart: always
    command: mysqld --general-log=1 --general-log-file=/var/log/mysql/general-log.log
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grayskull
