ServerConfiguration:
  meta:
    topLevel: false
  properties:
    baseUrl: string(1024)
    realmName: string(512)
    privateKey: string(16384)
    certificate: string(16384)

MailConfiguration:
  meta:
    topLevel: false
  properties:
    serverAddress: string
    username: string
    password: string
    sslEnabled: boolean
    port: integer
    fromAddress: string

SecurityConfiguration:
  meta:
    topLevel: false
    sensitive:
      - globalSecret
  properties:
    maxLoginAttemptsPerMinute: integer
    maxPasswordAge: integer
    passwordRequiresLowercase: boolean
    passwordRequiresUppercase: boolean
    passwordRequiresNumber: boolean
    passwordRequiresSymbol: boolean
    passwordMinimumLength: integer
    multifactorRequired: boolean
    requireEmailAddressVerification: boolean
    passwordHistoryEnabled: boolean
    passwordHistoryCount: integer
    invitationExpirationSeconds: integer
    accessTokenExpirationSeconds: integer
    globalSecret: string


Configuration:
  meta:
    topLevel: true
  properties:
    Security:
      modelRef: SecurityConfiguration
    Mail:
      modelRef: MailConfiguration
    Server:
      modelRef: ServerConfiguration
  operations:
    saveConfiguration:
      returns: OperationResponse
      arguments:
        Security: 
        Mail: 
        Server: 


