name: Master CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  master_build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1
      - name: Install Package Dependencies
        run: yarn install
      - name: Check formatting
        run: yarn format
      - name: Lint
        run: yarn lint
      - name: Tests
        run: yarn test
      - name: Compile
        run: yarn build
