name: Master CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  master_build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1
      - name: Create Test Database
        run: mysql -uroot -proot -h127.0.0.1 --force -e "CREATE DATABASE grayskull"
      - name: Install Package Dependencies
        run: yarn install
      - name: Start instance
        run: yarn start &
        env:
          GRAYSKULL_DB_CONNECTION_STRING: mysql://root:root@localhost/grayskull
          GRAYSKULL_GLOBAL_SECRET: TEST_ENVIRONMENT
      - name: Wait for startup
        run: sleep 7
      - name: Prepare for test test
        run: curl http://localhost:3000/api/__prepare_test_environment
      - name: Check formatting
        run: yarn format
      - name: Lint
        run: yarn lint
      - name: Foundation tests
        run: yarn test-foundation
      - name: Operations tests
        run: yarn test-operations
      - name: Activity tests
        run: yarn test-activities
      - name: Resolver tests
        run: yarn test-resolvers
      - name: Update release notes
        run: yarn update-release-notes

      - name: Compile
        run: yarn build
